package oasis.services.userdirectory;

import javax.inject.Inject;

import org.joda.time.LocalDate;

import com.google.common.base.Function;
import com.google.common.collect.Iterables;

import oasis.model.accounts.AccountRepository;
import oasis.model.accounts.Address;
import oasis.model.accounts.UserAccount;
import oasis.model.directory.OrganizationMembership;
import oasis.model.directory.OrganizationMembershipRepository;

@Deprecated
public class UserDirectoryService {

  private final AccountRepository accountRepository;
  private final OrganizationMembershipRepository organizationMemberRepository;

  @Inject
  UserDirectoryService(AccountRepository accountRepository,
      OrganizationMembershipRepository organizationMemberRepository) {
    this.accountRepository = accountRepository;
    this.organizationMemberRepository = organizationMemberRepository;
  }

  public AgentInfo getAgentInfo(String agentId) {
    UserAccount agent = accountRepository.getUserAccountById(agentId);
    OrganizationMembership membership = organizationMemberRepository.getOrganizationForUserIfUnique(agentId);
    return new AgentInfo(agent, membership);
  }

  public Iterable<AgentInfo> getAgentsForOrganization(String organizationId, int start, int limit) {
    Iterable<OrganizationMembership> memberships = organizationMemberRepository.getMembersOfOrganization(organizationId, start, limit);
    return Iterables.transform(memberships, new Function<OrganizationMembership, AgentInfo>() {
      @Override
      public AgentInfo apply(OrganizationMembership membership) {
        return getAgentInfo(membership.getAccountId());
      }
    });
  }

  public AgentInfo createAgentAccount(String organizationId, AgentInfo agentInfo) {
    UserAccount agent = createUserAccount(agentInfo);
    UserAccount createdAgentAccount = accountRepository.createUserAccount(agent);

    OrganizationMembership membership = new OrganizationMembership();
    membership.setAccountId(agent.getId());
    membership.setOrganizationId(agentInfo.getOrganization_id());
    membership.setAdmin(agentInfo.isOrganization_admin() == null ? false : agentInfo.isOrganization_admin());
    OrganizationMembership createdMembership = organizationMemberRepository.createOrganizationMembership(membership);
    // TODO: handle errors

    return new AgentInfo(createdAgentAccount, createdMembership);
  }

  private UserAccount createUserAccount(AgentInfo agentInfo) {
    UserAccount res = new UserAccount();

    // XXX: don't copy the ID, it should be generated by the repository, not provided by the caller of the API
    res.setUpdatedAt(agentInfo.getModified());

    res.setPicture(agentInfo.getPicture());
    res.setZoneInfo(agentInfo.getZoneinfo());
    res.setLocale(agentInfo.getLocale());
    res.setEmailAddress(agentInfo.getEmail());

    // Address
    if (agentInfo.getAddress() != null) {
      Address address = new Address();
      address.setCountry(agentInfo.getAddress().getCountry());
      address.setLocality(agentInfo.getAddress().getLocality());
      address.setPostalCode(agentInfo.getAddress().getPostal_code());
      address.setRegion(agentInfo.getAddress().getRegion());
      address.setStreetAddress(agentInfo.getAddress().getStreet_address());
      res.setAddress(address);
    }

    res.setName(agentInfo.getName());
    res.setFamilyName(agentInfo.getFamily_name());
    res.setGivenName(agentInfo.getGiven_name());
    res.setNickname(agentInfo.getNickname());
    res.setMiddleName(agentInfo.getMiddle_name());
    res.setGender(agentInfo.getGender());
    if (agentInfo.getBirthdate() != null) {
      res.setBirthdate(LocalDate.parse(agentInfo.getBirthdate()));
    }
    res.setPhoneNumber(agentInfo.getPhone());
    res.setPhoneNumberVerified(agentInfo.isPhone_verified() == null ? false : agentInfo.isPhone_verified());
    res.setUpdatedAt(agentInfo.getUpdated_at() == null ? 0 : agentInfo.getUpdated_at());

    return res;
  }
}
