mod "system_tools",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/system_tools.git",
  :ref => '61807b1d4410c760c78dca72c9013675ab4360f8'

# needed by system_tools :
# * stdlib
# * apt
# * download_file
# * augeas
# * ntp
# * puppet
# * timezone
# * snmpd
# * xinetd
# * firewall

mod "stdlib",
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git",
  :ref => '4d24bd33b038aaf261342641e14fdced1371fe8d'

mod "apt",
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git",
  :ref => 'e01bbb61b294be1358b147e8de4966d5f4c6efda'

mod "download_file",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-download_file.git",
  :ref => 'e4e4144447ee8ad54d6a1e359535b3586a727d47'

mod "augeas",
  :git => "git://github.com/camptocamp/puppet-augeas.git",
  :ref => '1afd076a152f43645c91b1e2bab15fda7498055c'

mod "ntp",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/ntp.git",
  :ref => 'a00b999bc610d93caa9c496d00a22888e9e682ba'

mod "puppet",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/puppet.git",
  :ref => '5245eb622af35b7a7624221e99bbcd48ceb82150'

mod "timezone",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/timezone.git",
  :ref => 'b205ed592f9ae105bcd237425dc6d7b7d56d518b'

mod "snmpd",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/snmpd.git",
  :ref => '49649c413dfa6b45ba87f86dbdb275d060a565b3'

mod "xinetd",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/xinetd.git",
  :ref => '97a342099bdba7958601f167fb43432b04735cdd'

mod "firewall",
  :git => "git://github.com/puppetlabs/puppetlabs-firewall.git",
  :ref => '31b45bf88129870e4e028847e5a8955130f68e32'

# end of system_tools dependencies

mod "java",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/java.git",
  :ref => 'd21ee3ed43a8de0cf7c627f92c5b5859d54d12c4'

mod "fluentd",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/fluentd.git",
  :ref => "1d28c2c3fc7df014f4fa8c6296b03ff4a713d69c"

# needed by fluentd :
# * augeasproviders
# * ruby

mod "augeasproviders",
  :git => "git://github.com/hercules-team/augeasproviders.git",
  :ref => 'be18e2ee3803bfe39dced1fa9113b4e87139e857'

mod "ruby",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/ruby.git",
  :ref => "e96f7889ce9d62007624d89dbdc89d74ddc57a39"

# end of fluentd dependencies

mod "elasticsearch",
  :git => "https://github.com/elasticsearch/puppet-elasticsearch.git",
  :ref => "0244c435e65d29eb3f5b800c38c55bc0a7eb384e"

