#! /bin/sh

case "$1" in
  install|upgrade)

  # If the package has default file it could be sourced, so that
  # the local admin can overwrite the defaults

  [ -f "/etc/default/@name@" ] && . /etc/default/@name@

  SERVICE_HOME="@oasis.home@"
  SERVICE_NAME="@oasis.desc@"

  # Sane defaults:

  [ -z "$SERVICE_USER" ] && SERVICE_USER="@oasis.user@"
  [ -z "$SERVICE_GROUP" ] && SERVICE_GROUP="@oasis.group@"

  # create user to avoid running server as root

  # 1. create group if not existing
  if ! getent group | grep -q "^$SERVICE_GROUP:" ; then
    echo -n "Adding group $SERVICE_GROUP.."
    addgroup --quiet --system $SERVICE_GROUP 2>/dev/null ||true
    echo "..done"
  fi

  # 2. create homedir if not existing
  test -d $SERVICE_HOME || mkdir $SERVICE_HOME

  # 3. create user if not existing

  if ! getent passwd | grep -q "^$SERVICE_USER:"; then
    echo -n "Adding system user $SERVICE_USER.."
    adduser --quiet \
            --system \
            --ingroup $SERVICE_GROUP \
            --no-create-home \
            --disabled-password \
            $SERVICE_USER 2> /dev/null || true
    echo "..done"
  fi

  # 4. adjust passwd entry
  usermod -c "$SERVICE_NAME" \
          -d $SERVICE_HOME   \
          -g $SERVICE_GROUP  \
             $SERVICE_USER 2> /dev/null

  ;;

  configure)
  ;;
esac
