# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "debian-7-64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://software.atolcd.priv/vagrant/debian-7-64.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  #config.vm.boot_mode = :gui

  config.vm.host_name = "oasis-box.atolcd.priv"

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  #config.vm.network :hostonly, "33.33.33.10"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as another
  # physical device on your network.
  #config.vm.network :bridged

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port 8080, 8080 # Oasis
  config.vm.forward_port 9200, 9200 # ElasticSearch port
  config.vm.forward_port 9880, 9880 # Fluentd in_http port
  config.vm.forward_port 27017, 27017 # Mongodb

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  config.vm.share_folder "v-project-root", "/project/", "../../"
  config.vm.share_folder "v-apt-cache", "/var/cache/apt/archives", "~/.vagrant.d/cache/apt"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../manifests"
    puppet.manifest_file  = "oasis-vagrant.pp"
    puppet.module_path    = "../modules/deps","../modules/project"
  end

  config.vm.customize ["modifyvm", :id, "--memory", "1024"]
  config.vm.customize ["modifyvm", :id, "--cpus", "2"]
end

