mod "system_tools",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/system_tools.git"

# needed by system_tools :
# * stdlib
# * apt
# * download_file
# * augeas
# * ntp
# * puppet
# * timezone
# * snmpd
# * xinetd
# * firewall

mod "stdlib",
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git",
  :ref => '3.2.0'

mod "apt",
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git",
  :ref => 'e01bbb61b294be1358b147e8de4966d5f4c6efda'

mod "download_file",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-download_file.git"

mod "augeas",
  :git => "git://github.com/camptocamp/puppet-augeas.git",
  :ref => '1afd076a152f43645c91b1e2bab15fda7498055c'

mod "ntp",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/ntp.git",
  :ref => 'a00b999bc610d93caa9c496d00a22888e9e682ba'

mod "puppet",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/puppet.git",
  :ref => '5245eb622af35b7a7624221e99bbcd48ceb82150'

mod "timezone",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/timezone.git",
  :ref => 'b205ed592f9ae105bcd237425dc6d7b7d56d518b'

mod "snmpd",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/snmpd.git",
  :ref => '49649c413dfa6b45ba87f86dbdb275d060a565b3'

mod "xinetd",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/xinetd.git",
  :ref => '97a342099bdba7958601f167fb43432b04735cdd'

mod "firewall",
  :git => "git://github.com/puppetlabs/puppetlabs-firewall.git",
  :ref => '31b45bf88129870e4e028847e5a8955130f68e32'

# end of system_tools dependencies

mod "java",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/java.git",
  :ref => 'd21ee3ed43a8de0cf7c627f92c5b5859d54d12c4'

mod "elasticsearch",
  :git => "https://github.com/elasticsearch/puppet-elasticsearch.git",
  :ref => "0244c435e65d29eb3f5b800c38c55bc0a7eb384e"

mod "mongodb",
  :git => "http://gerrit.atolcd.priv/atolcd/puppet-modules/mongodb.git",
  :ref => "0049818b740cdfb3cc04b27617ee6a881e69fdf0"

mod "logstash",
  :git => "https://github.com/logstash/puppet-logstash.git"
